### ISSUE TITLE
SyntaxError: Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by eugeneievlev** [idealo/cloudwatch-alarm-to-ms-teams#265]
Hi there,

The app has been deployed from AWS Serverless Application Repository.
The error occurs when Publish message from SNS console.

```
{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected token T in JSON at position 0",
    "stack": [
        "SyntaxError: Unexpected token T in JSON at position 0",
        "    at JSON.parse (<anonymous>)",
        "    at Runtime.handler (/var/task/dist/handlers/forward-to-teams.js:40:30)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1147:29)"
    ]
}
```

Regards,
Eugene

**Comment by eserte** [comment]
The error message looks like you were sending non-JSON data to the topic. Actually you would need to create the very exact JSON structure as Cloudwatch would do it.
